apiPrefix: /api/v1
spring:
  mvc:
    problemdetails:
      enabled: true
  application:
    name: reeve-indexing-example
  flyway:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    schemas: ${DB_SCHEMA:reeve_verifier}
    locations: classpath:db/store/{vendor}
    out-of-order: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=reeve_verifier}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    hibernate:
      ddl-auto: none
    #show-sql: true

reeve:
  script-path: ${REEVE_SCRIPT_PATH:./aiken/plutus.json}
  label: 1447
  dashboard-folder-path: ./dashboards
store:
  cardano:
    host: backbone.mainnet.cardanofoundation.org
    port: 3001
    protocol-magic: 764824073
    sync-start-slot: 159983856
    sync-start-blockhash: 739cbc4d7ae7a15805ce2ede010b3a24c6d2e18489e3940731822f9f5488d670
  executor:
    enable-parallel-processing: false
  core:
    enabled: true
  metadata:
    api-enabled: false
server:
  port: 9000


keri:
  enabled: false
  metadata-label: 1
  url: ${KERI_URL:http://127.0.0.1:1901}
  bootUrl: ${KERI_BOOT_URL:http://127.0.0.1:1903}
  oobis: ${KERI_OOBIS:http://keria:3902/oobi/EJO54wp79Apo4pOyAloOVQw9BQlVohycPWV0FaurG8Br/agent/EOS8r7jbPS1rYKR7duLMfuSwQsNUuUPmuFq4b-ORm9ih}
