apiPrefix: /api/v1
spring:
  mvc:
    problemdetails:
      enabled: true
  application:
    name: reeve-indexing-example
  flyway:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    schemas: ${DB_SCHEMA:reeve_verifier}
    locations: classpath:db/store/{vendor}
    out-of-order: true
    cleanDisabled: ${FLYWAY_CLEAN_DISABLED:false}
    cleanOnValidationError: ${FLYWAY_CLEAN_ON_ERROR:true}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=reeve_verifier}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    hibernate:
      ddl-auto: none
reeve:
  script-path: ${REEVE_SCRIPT_PATH:./aiken/plutus.json}
  label: 1447
  dashboard-folder-path: ./dashboards
store:
  cardano:
    host: yaci-cli
    port: 3001
    protocol-magic: 42
    # for devnet we must specify the genesis files for Yaci-Store
    byron-genesis-file: classpath:/devel/config/devkit/byron-genesis.json
    shelley-genesis-file: classpath:/devel/config/devkit/shelley-genesis.json
    alonzo-genesis-file: classpath:/devel/config/devkit/alonzo-genesis.json
    conway-genesis-file: classpath:/devel/config/devkit/conway-genesis.json
    sync-start-blockhash:
    sync-start-slot: 0
  executor:
    enable-parallel-processing: false
  core:
    enabled: true
  metadata:
    api-enabled: false
server:
  port: 9000

keri:
  enabled: false
  metadata-label: 1
  url: ${KERI_URL:http://127.0.0.1:1901}
  bootUrl: ${KERI_BOOT_URL:http://127.0.0.1:1903}
  oobis: ${KERI_OOBIS:http://keria:3902/oobi/EJO54wp79Apo4pOyAloOVQw9BQlVohycPWV0FaurG8Br/agent/EOS8r7jbPS1rYKR7duLMfuSwQsNUuUPmuFq4b-ORm9ih}
