apiPrefix: /api/v1
spring:
  mvc:
    problemdetails:
      enabled: true
  application:
    name: reeve-indexing-example
  flyway:
    locations: classpath:db/store/{vendor}
    out-of-order: true
  datasource:
    url: jdbc:postgresql://localhost:5432/reeve-verifier?currentSchema=reeve
    username: postgres
    password: postgres
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    hibernate:
      ddl-auto: update
reeve:
  label: 1447
  dashboard-folder-path: ./dashboards
store:
  cardano:
    host: backbone.mainnet.cardanofoundation.org
    port: 3001
    protocol-magic: 764824073
    sync-start-slot: 159983856
    sync-start-blockhash: 739cbc4d7ae7a15805ce2ede010b3a24c6d2e18489e3940731822f9f5488d670
  executor:
    enable-parallel-processing: true
    block-processing-threads: 15
    event-processing-threads: 30
    blocks-batch-size: 200
    blocks-partition-size: 10
    use-virtual-thread-for-batch-processing: true
    use-virtual-thread-for-event-processing: true
  core:
    enabled: true
  metadata:
    api-enabled: false
server:
  port: 9000
