apiPrefix: /api/v1
spring:
  mvc:
    problemdetails:
      enabled: true
  application:
    name: reeve-indexing-example
  flyway:
    locations: classpath:db/store/{vendor}
    out-of-order: true
  datasource:
    url: jdbc:postgresql://localhost:5433/reeve-verifier?currentSchema=reeve
    username: postgres
    password: postgres
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    hibernate:
      ddl-auto: update
reeve:
  label: 1447
  dashboard-folder-path: ./dashboards
store:
  cardano:
    host: 127.0.0.1
    port: 3001
    # 42 is protocol magic for Yaci-Dev-Kit
    protocol-magic: 42
    # for devnet we must specify the genesis files for Yaci-Store
    byron-genesis-file: classpath:/devel/config/devkit/byron-genesis.json
    shelley-genesis-file: classpath:/devel/config/devkit/shelley-genesis.json
    alonzo-genesis-file: classpath:/devel/config/devkit/alonzo-genesis.json
    conway-genesis-file: classpath:/devel/config/devkit/conway-genesis.json

    sync-start-blockhash:
    sync-start-slot: 0
  executor:
    enable-parallel-processing: true
    block-processing-threads: 15
    event-processing-threads: 30
    blocks-batch-size: 200
    blocks-partition-size: 10
    use-virtual-thread-for-batch-processing: true
    use-virtual-thread-for-event-processing: true
  core:
    enabled: true
  metadata:
    api-enabled: false
server:
  port: 9000
